---
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  annotated_tag: true
  version: 8.1.24.post3
  version_files:
  - src/system/__version__.py
  update_changelog_on_bump: true
  
