[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = 2.7

[tool.isort]
profile = "black"

[tool.pydocstyle]
convention = "google"
add_ignore = ["D205", "D415"]
match_dir = "system"
