name: ci

on:
  pull_request:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    name: tox
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('.pre-commit-config.yaml', '.pylintrc', 'tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Run tests
        run: |
          tox
