name: ci

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/ci.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'mypy[python2]'
        python -m pip install pylint
    - name: Analysing the code with mypy
      run: |
        mypy src
    - name: Analysing the code with pylint
      run: |
        pylint src
