name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: coatl-dev/workflows/.github/workflows/tox-docker.yml@v6
    with:
      pre-commit: true
