name: publish

on:
  release:
    types:
      - published

jobs:
  main:
    uses: thecesrom/workflows/.github/workflows/pypi-upload.yml@v0.1.0
    with:
      image: ubuntu-20.04
      python-version: "2.7"
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_PKG }}
