name: publish

on:
  release:
    types:
      - published

jobs:
  pre-commit:
    uses: coatl-dev/workflows/.github/workflows/pre-commit.yml@coatl
    with:
      skip-hooks: 'pylint'

  pylint:
    needs: pre-commit
    uses: coatl-dev/workflows/.github/workflows/pylint.yml@coatl

  tox:
    needs:
      - pre-commit
      - pylint
    uses: coatl-dev/workflows/.github/workflows/tox-docker.yml@coatl

  pypi-publish:
    needs:
      - pre-commit
      - pylint
      - tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: coatl-dev/actions/pypi-upload@coatl
        with:
          password: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_PKG }}
