name: pypi_upload

on:
  release:
    types:
      - published

jobs:
  build:

    name: PyPI Upload

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install latest pip, setuptools, twine + wheel
        run: |
          python -m pip install --upgrade pip setuptools twine wheel

      - name: Build wheels
        run: |
          python setup.py bdist_wheel
          python setup.py sdist

      - name: Twine check
        run: |
          python -m twine check dist/*

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --verbose --username '__token__' dist/*
